### ISSUE TITLE
Support for nested ymlv-config

### ISSUE THREAD

**Issue by RickardCardell** [klarna-incubator/bec#63]
I would like to request support for more complex structures in the ymlv-config.

Currently the config in an ymlv-file may be a list of maps:

```
---
- project: MYTEAM
  repo: my_repo
  has_ci: true

- project: MYTEAM
  repo: best_cat_pics
  has_ci: false
  ```

However, it's not uncommon to have a more nested structure. E.g one want to define multiple webhooks for a repo:
```
- repo: "foobar"
  webhooks:
    - name: "on-merge"
      events:
        - name: "pr:merged"
        - name: "repo:refs-Changed"
    - name: "on-commit"
      events:
        - name: "pr:merged"
        - name: "repo:som-event"

 ```
Current behavior:

```
escript: exception error: no function clause matching
                 bec_yml:to_mustache([#{<<"events">> =>
                                            [#{<<"name">> => <<"pr:merged">>},
                                             #{<<"name">> =>
                                                   <<"repo:refs-Changed">>}],
                                        <<"name">> => <<"on-merge">>},
                                      #{<<"events">> =>
                                            [#{<<"name">> => <<"pr:merged">>},
                                             #{<<"name">> =>
                                                   <<"repo:som-event">>}],
                                        <<"name">> => <<"on-commit">>}]) (dev/github/klarna-incubator/bec/src/bec_yml.erl, line 33)
  in function  bitbucket_repo_config:'-read_vars/1-fun-1-'/3 (dev/github/klarna-incubator/bec/src/bitbucket_repo_config.erl, line 56)
  in call from maps:fold_1/3 (maps.erl, line 411)
  in call from lists:map/2 (lists.erl, line 1315)
  in call from bitbucket_repo_config:verify/2 (dev/github/klarna-incubator/bec/src/bitbucket_repo_config.erl, line 28)
  in call from bec:do_main/1 (dev/github/klarna-incubator/bec/src/bec.erl, line 51)
  ´´´
